//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSChecker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("37530159341115681")]
        public string AODRId {
            get {
                return ((string)(this["AODRId"]));
            }
            set {
                this["AODRId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("37530159341130061")]
        public string AODCId {
            get {
                return ((string)(this["AODCId"]));
            }
            set {
                this["AODCId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("37530159341133378")]
        public string AODSId {
            get {
                return ((string)(this["AODSId"]));
            }
            set {
                this["AODSId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("census.daybreakgames.com")]
        public string DaybreakURL {
            get {
                return ((string)(this["DaybreakURL"]));
            }
            set {
                this["DaybreakURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xml")]
        public string DaybreakResponseFormat {
            get {
                return ((string)(this["DaybreakResponseFormat"]));
            }
            set {
                this["DaybreakResponseFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ps2:v2")]
        public string DaybreakPlanetsideQuery {
            get {
                return ((string)(this["DaybreakPlanetsideQuery"]));
            }
            set {
                this["DaybreakPlanetsideQuery"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("317508044186-0crsurmrj4123blcb2jturlgnj7rnjs8.apps.googleusercontent.com")]
        public string DriveClientId {
            get {
                return ((string)(this["DriveClientId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CR9qK9rXaB8bxizV1MBN_WAh")]
        public string DriveClientSecret {
            get {
                return ((string)(this["DriveClientSecret"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0B8G9vu6N0EcCR3hfYTNWQW9SNDA")]
        public string DriveFileId {
            get {
                return ((string)(this["DriveFileId"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Planetside 2,AOD Racing,ARK,Armored Warfare,Battlefield,Battlefront,Black Desert," +
            "Jedi Knight,Overwatch,Skyforge,Tom Clancy,Warframe,War Thunder,World of Warcraft" +
            "")]
        public string AOD_Divisions {
            get {
                return ((string)(this["AOD_Divisions"]));
            }
            set {
                this["AOD_Divisions"] = value;
            }
        }
    }
}
